Allow multiple checkins
Flaredown/FlaredownEmber-2 pull request #488
Opened 2021-10-12 19:33 UTC by haydenrou

#434

2021-10-13 13:27 UTC, bklang commented
Reminder from standup this morning, the Rails upgrades are steamrolling right along. I recommend rebasing this morning to pick up the Rails upgrades

2021-10-13 22:50 UTC, haydenrou commented
Accidentally pushed the fix for #496 here

2021-10-14 14:41 UTC, benlangfeld commented
You'll need to merge master into this PR to get CI to run properly again.

2021-10-14 20:51 UTC, compwron commented
Sounds wonderful! I'm looking forward to trying it out in staging :)

2021-10-14 20:59 UTC, phylum approved these changes

2021-10-14 21:13 UTC, lmerriam approved these changes
Screenshots look good

2021-10-14 21:14 UTC, compwron approved these changes

2021-10-14 22:09 UTC, bklang requested changes
Nice improvement! Only real objection is the `.tool-versions` files

2021-10-14 22:09 UTC, bklang commented on .tool-versions
> +ruby 2.7.4
These files should not be checked in because they conflict with the `.ruby-version` files

2021-10-14 22:09 UTC, bklang commented on backend/.tool-versions
> +ruby 2.7.4
Ditto

2021-10-14 22:09 UTC, bklang commented on frontend/.tool-versions
> +nodejs 12.22.6
This file should not be checked in because it conflicts with the `.nvmrc` file

2021-10-15 12:45 UTC, phylum approved these changes

2021-10-15 12:56 UTC, bklang approved these changes

2021-10-15 12:57 UTC, merged