signup button has been updated to meet styles throughout.  Also, unused color variable was removed
Flaredown/FlaredownEmber-2 pull request #532
Opened 2021-10-14 18:19 UTC by batistaDev1113

Fixed style on signup button. Also, removed unused variable from .scss file

Before
![create-account-active-before](https://user-images.githubusercontent.com/15971206/137373783-976e049a-a693-48f1-9c51-999e12291b42.jpg)

After

![create-account-active-after](https://user-images.githubusercontent.com/15971206/137373812-378c54c8-2dbe-49a6-9e1d-5afee2666e3e.png)

Thank you!

2021-10-14 18:46 UTC, bklang requested changes

2021-10-14 18:46 UTC, bklang commented on frontend/app/styles/_badges.scss
> +  // "default": $progress-gray,
If this is no longer needed, please remove it so we don't leave dead code lying around

2021-10-14 18:46 UTC, bklang commented on frontend/app/styles/bitters/_base.scss
> +
Please remove this change since it's not functional. We want to keep the difference focused on the described work

2021-10-14 19:14 UTC, batistaDev1113 commented on frontend/app/styles/_badges.scss
> +  // "default": $progress-gray,
My bad... we were testing the migration of a variable and I commented that variable to see the effect it had.  It is being used inside the _progressbar.scss file.  Already put back in 👍🏻

2021-10-14 19:49 UTC, batistaDev1113 commented on frontend/app/styles/_badges.scss
> +  // "default": $progress-gray,
All done... thank you!

2021-10-14 19:50 UTC, batistaDev1113 commented on frontend/app/styles/bitters/_base.scss
> +
Done... thank you @bklang

2021-10-15 13:36 UTC, bklang approved these changes

2021-10-15 13:36 UTC, merged